import * as ChamCongs from './cham-congs';
import * as CheDoNhanViens from './che-do-nhan-viens';
import * as CheDos from './che-dos';
import * as ChiNhanhs from './chi-nhanhs';
import * as ChucVus from './chuc-vus';
import * as HopDongs from './hop-dongs';
import * as Kpis from './kpis';
import * as LichLamViecs from './lich-lam-viecs';
import * as LuongNhanViens from './luong-nhan-viens';
import * as PhongBans from './phong-bans';
import * as PhuCapNhanViens from './phu-cap-nhan-viens';
export { ChamCongs, CheDoNhanViens, CheDos, ChiNhanhs, ChucVus, HopDongs, Kpis, LichLamViecs, LuongNhanViens, PhongBans, PhuCapNhanViens };
